# Generated by Django 4.2.5 on 2023-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurments_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurments',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='температура'),
        ),
    ]
